snowflake:
  target: snowflake
  outputs:
    snowflake:
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DB') }}"
      private_key_path: "{{ env_var('DBT_SNOWFLAKE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_KEY_PASS') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      schema: donotuse
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WH') }}"
