name: Snowflake-Reporting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        env:
          DBT_ENV_SECRET_SF_REPORTING_REPO_KEY: ${{ secrets.DBT_ENV_SECRET_SF_REPORTING_REPO_KEY }}
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Build DBT project
        run: dbt build
