name: Snowflake-Reporting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install dbt dependencies
        env:
          DBT_ENV_SECRET_SF_REPORTING_REPO_KEY: ${{ secrets.DBT_ENV_SECRET_SF_REPORTING_REPO_KEY }}
        run: |
          dbt deps

      - name: Build DBT project
        env:
          DBT_SNOWFLAKE_ACCOUNT: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_DB: ${{ vars.DBT_SNOWFLAKE_DB }}
          DBT_SNOWFLAKE_KEY: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_KEY_PASS: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_ROLE: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_USER: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_WH: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
        run: |
          echo $DBT_SNOWFLAKE_ACCOUNT
          dbt build
