name: Snowflake-Reporting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install dbt dependencies
        env:
          DBT_ENV_SECRET_SF_REPORTING_REPO_KEY: ${{ secrets.DBT_ENV_SECRET_SF_REPORTING_REPO_KEY }}
        run: |
          dbt deps

      - name: Debug DBT
        env:
          DBT_ENV_SECRET_SF_REPORTING_REPO_KEY: ${{ secrets.DBT_ENV_SECRET_SF_REPORTING_REPO_KEY }}
          DBT_SNOWFLAKE_ACCOUNT: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_DB: ${{ vars.DBT_SNOWFLAKE_DB }}
          #DBT_SNOWFLAKE_KEY: ${{ secrets.DBT_SNOWFLAKE_KEY }}
          DBT_SNOWFLAKE_KEY: ${{ vars.DBT_SNOWFLAKE_KEY_B24 }}
          DBT_SNOWFLAKE_KEY_PASS: ${{ secrets.DBT_SNOWFLAKE_KEY_PASS }}
          DBT_SNOWFLAKE_ROLE: ${{ vars.DBT_SNOWFLAKE_ROLE }}
          DBT_SNOWFLAKE_USER: ${{ vars.DBT_SNOWFLAKE_USER }}
          DBT_SNOWFLAKE_WH: ${{ vars.DBT_SNOWFLAKE_WH }}
        run: |
          echo $DBT_SNOWFLAKE_KEY | base64 -d > snowflake_rsa_key.p8
          cat snowflake_rsa_key.p8
          DBT_SNOWFLAKE_KEY_PATH=$(pwd)
          echo "Current Directory: DBT_SNOWFLAKE_KEY_PATH"
          echo "DBT_SNOWFLAKE_KEY_PATH=DBT_SNOWFLAKE_KEY_PATH" >> $GITHUB_ENV
          echo $DBT_SNOWFLAKE_KEY_PATH
          dbt debug

      - name: Build DBT project
        env:
          DBT_ENV_SECRET_SF_REPORTING_REPO_KEY: ${{ secrets.DBT_ENV_SECRET_SF_REPORTING_REPO_KEY }}
          DBT_SNOWFLAKE_ACCOUNT: ${{ vars.DBT_SNOWFLAKE_ACCOUNT }}
          DBT_SNOWFLAKE_DB: ${{ vars.DBT_SNOWFLAKE_DB }}
          DBT_SNOWFLAKE_KEY: ${{ vars.DBT_SNOWFLAKE_KEY }}
          DBT_SNOWFLAKE_KEY_PASS: ${{ secrets.DBT_SNOWFLAKE_KEY_PASS }}
          DBT_SNOWFLAKE_ROLE: ${{ vars.DBT_SNOWFLAKE_ROLE }}
          DBT_SNOWFLAKE_USER: ${{ vars.DBT_SNOWFLAKE_USER }}
          DBT_SNOWFLAKE_WH: ${{ vars.DBT_SNOWFLAKE_WH }}
        run: |
          echo $DBT_SNOWFLAKE_ACCOUNT
          dbt build
